# Generated by Django 5.1.4 on 2025-01-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('faction', models.CharField(max_length=200)),
                ('card_type', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=200)),
                ('generic_cost', models.IntegerField()),
                ('faction_cost', models.CharField(max_length=200)),
                ('attack', models.IntegerField()),
                ('health', models.IntegerField()),
                ('serial_number', models.IntegerField()),
                ('text_box', models.TextField()),
                ('rules_explanation', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=200)),
                ('set_code', models.CharField(max_length=200)),
                ('released_date', models.DateField()),
                ('total_cards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_art', models.ImageField(upload_to='')),
                ('label', models.CharField(max_length=200)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoGDB.card')),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoGDB.cardset')),
            ],
        ),
    ]
