# Generated by Django 5.1.4 on 2025-01-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=200)),
                ('format_desc', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='faction_cost',
        ),
        migrations.RemoveField(
            model_name='card',
            name='generic_cost',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='card',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='card',
            name='converted_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cardset',
            name='set_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='faction',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rules_explanation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_box',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='total_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('rarity', models.CharField(max_length=200)),
                ('card_art', models.ImageField(upload_to='')),
                ('artist', models.CharField(max_length=200)),
                ('label', models.CharField(default='', max_length=200)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoGDB.card')),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoGDB.cardset')),
            ],
        ),
        migrations.CreateModel(
            name='FormatFollows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legality', models.CharField(choices=[('L', 'Legal'), ('B', 'Prohibida'), ('NL', 'No legal')], max_length=3)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoGDB.card')),
                ('format_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoGDB.format')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecificCard',
        ),
    ]
