# Generated by Django 5.1.4 on 2025-01-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0005_alter_cardversion_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='set_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='card_art',
            field=models.ImageField(blank=True, upload_to='card_art'),
        ),
    ]
