# Generated by Django 5.1.4 on 2025-01-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0008_alter_cardversion_card_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardversion',
            name='card_art',
            field=models.ImageField(blank=True, upload_to='media/card_art'),
        ),
    ]
