# Generated by Django 5.1.4 on 2025-01-17 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0013_otherlanguagecard_card_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='related_cards',
            field=models.ManyToManyField(blank=True, to='RoGDB.card'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RoGDB.cardset'),
        ),
        migrations.AlterField(
            model_name='formatfollows',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RoGDB.card'),
        ),
    ]
