# Generated by Django 5.1.4 on 2025-01-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0015_alter_card_attack_alter_card_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_token',
            field=models.BooleanField(default=False),
        ),
    ]
