# Generated by Django 5.1.4 on 2025-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0016_card_is_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardversion',
            options={'get_latest_by': '-pk'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_token',
        ),
        migrations.AddField(
            model_name='cardversion',
            name='last_print',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='legality',
            field=models.ManyToManyField(blank=True, to='RoGDB.format'),
        ),
    ]
