# Generated by Django 5.1.4 on 2025-01-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0017_alter_cardversion_options_remove_card_is_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardversion',
            name='rarity',
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(default='Rara', max_length=200),
            preserve_default=False,
        ),
    ]
