# Generated by Django 5.1.4 on 2025-02-01 17:45

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0018_remove_cardversion_rarity_card_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='faction',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('J', 'Jupiter'), ('M', 'Marte'), ('N', 'Neptuno'), ('P', 'Pluton'), ('S', 'Saturno')], max_length=9),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[(0, 'Común'), (1, 'Rara'), (2, 'Epica'), (3, 'Legendaria')], max_length=200),
        ),
    ]
