# Generated by Django 5.1.4 on 2025-02-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0019_alter_card_faction_alter_card_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardversion',
            name='is_skin',
            field=models.BooleanField(default=False),
        ),
    ]
