# Generated by Django 5.1.4 on 2025-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0020_cardversion_is_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.IntegerField(choices=[(0, 'Común'), (1, 'Rara'), (2, 'Epica'), (3, 'Legendaria')]),
        ),
    ]
