# Generated by Django 5.1.4 on 2025-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0022_alter_card_faction_alter_card_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardversion',
            name='legality',
        ),
        migrations.AddField(
            model_name='card',
            name='legality',
            field=models.ManyToManyField(blank=True, through='RoGDB.FormatFollows', to='RoGDB.format'),
        ),
    ]
