# Generated by Django 5.1.4 on 2025-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0023_remove_cardversion_legality_card_legality'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='card_id',
            field=models.ManyToManyField(through='RoGDB.FormatFollows', to='RoGDB.card', verbose_name='Card'),
        ),
    ]
