# Generated by Django 5.1.6 on 2025-10-08 15:54

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0025_rename_legality_card_card_legality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_name'], 'verbose_name': 'Carta', 'verbose_name_plural': 'Cartas'},
        ),
        migrations.AlterModelOptions(
            name='cardset',
            options={'ordering': ['-released_date'], 'verbose_name': 'Set', 'verbose_name_plural': 'Expansiones'},
        ),
        migrations.AlterModelOptions(
            name='cardversion',
            options={'get_latest_by': '-pk', 'verbose_name': 'Versión de carta', 'verbose_name_plural': 'Versiones de cartas'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Formato', 'verbose_name_plural': 'Formatos'},
        ),
        migrations.AlterModelOptions(
            name='formatfollows',
            options={'verbose_name': 'Legalidad de carta', 'verbose_name_plural': 'Legalidades de cartas'},
        ),
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ataque'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_legality',
            field=models.ManyToManyField(blank=True, through='RoGDB.FormatFollows', to='RoGDB.format', verbose_name='Legalidad'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=200, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='converted_cost',
            field=models.IntegerField(default=0, verbose_name='Coste convertido'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.CharField(default='', max_length=30, verbose_name='Coste'),
        ),
        migrations.AlterField(
            model_name='card',
            name='faction',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('J', 'Jupiter'), ('M', 'Marte'), ('N', 'Neptuno'), ('P', 'Pluton'), ('S', 'Saturno'), ('T', 'Tierra')], max_length=11, verbose_name='Facción'),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.IntegerField(choices=[(0, 'Token'), (1, 'Común'), (2, 'Rara'), (3, 'Épica'), (4, 'Legendaria')], verbose_name='Rareza'),
        ),
        migrations.AlterField(
            model_name='card',
            name='related_cards',
            field=models.ManyToManyField(blank=True, to='RoGDB.card', verbose_name='Cartas relacionadas'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rules_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Explicación de reglas'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_box',
            field=models.TextField(blank=True, default='', verbose_name='Habilidad'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='released_date',
            field=models.DateField(verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_type',
            field=models.CharField(default='', max_length=200, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='total_cards',
            field=models.IntegerField(default=0, verbose_name='Cantidad de cartas'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='artist',
            field=models.CharField(max_length=200, verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='card_art',
            field=models.ImageField(blank=True, upload_to='media/card_art', verbose_name='Arte'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoGDB.card', verbose_name='Carta'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='flavor_text',
            field=models.TextField(blank=True, default='', verbose_name='Texto de ambientación (Flavor)'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='is_skin',
            field=models.BooleanField(default=False, verbose_name='¿Es una skin?'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='last_print',
            field=models.BooleanField(default=True, verbose_name='Última impresión'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='serial_number',
            field=models.IntegerField(verbose_name='Código de carta'),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RoGDB.cardset', verbose_name='Set'),
        ),
        migrations.AlterField(
            model_name='format',
            name='card_id',
            field=models.ManyToManyField(through='RoGDB.FormatFollows', to='RoGDB.card', verbose_name='Carta'),
        ),
        migrations.AlterField(
            model_name='format',
            name='format_desc',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='format',
            name='format_name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='formatfollows',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RoGDB.card', verbose_name='Carta'),
        ),
        migrations.AlterField(
            model_name='formatfollows',
            name='format_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoGDB.format', verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='formatfollows',
            name='legality',
            field=models.CharField(choices=[('L', 'Legal'), ('B', 'Prohibida'), ('N', 'No legal')], default='L', max_length=3, verbose_name='Legalidad'),
        ),
    ]
