# Generated by Django 5.1.6 on 2025-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0026_alter_card_options_alter_cardset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='¿Es visible?'),
        ),
    ]
