# Generated by Django 5.1.4 on 2025-01-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0002_format_remove_card_faction_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_name']},
        ),
        migrations.AlterModelOptions(
            name='cardset',
            options={'ordering': ['-released_date']},
        ),
        migrations.AddField(
            model_name='cardversion',
            name='flavor_text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rules_explanation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_box',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='formatfollows',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RoGDB.card'),
        ),
        migrations.AlterField(
            model_name='formatfollows',
            name='legality',
            field=models.CharField(choices=[('L', 'Legal'), ('B', 'Prohibida'), ('N', 'No legal')], default='L', max_length=3),
        ),
    ]
