# Generated by Django 5.1.4 on 2025-01-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0003_alter_card_options_alter_cardset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='rules_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_box',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cardversion',
            name='flavor_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
