# Generated by Django 5.1.4 on 2025-01-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0004_alter_card_attack_alter_card_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardversion',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
