# Generated by Django 5.1.4 on 2025-01-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0009_alter_cardversion_card_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='related_cards',
            field=models.ManyToManyField(to='RoGDB.card'),
        ),
        migrations.AddField(
            model_name='cardversion',
            name='legality',
            field=models.ManyToManyField(to='RoGDB.format'),
        ),
        migrations.CreateModel(
            name='OtherLanguageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Ingles'), ('zh', 'Chino'), ('pt', 'Portugues')], default='es', max_length=3)),
                ('original_card_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RoGDB.cardversion')),
            ],
        ),
    ]
