# Generated by Django 5.1.4 on 2025-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0010_card_related_cards_cardversion_legality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='related_cards',
            field=models.ManyToManyField(blank=True, to='RoGDB.card'),
        ),
    ]
