# Generated by Django 5.1.4 on 2025-01-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoGDB', '0012_alter_card_related_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherlanguagecard',
            name='card_art',
            field=models.ImageField(blank=True, upload_to='media/card_art'),
        ),
        migrations.AddField(
            model_name='otherlanguagecard',
            name='trans_flavor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='otherlanguagecard',
            name='trans_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='otherlanguagecard',
            name='trans_text_box',
            field=models.TextField(blank=True, default=''),
        ),
    ]
