# Generated by Django 5.1.4 on 2025-01-30 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=100)),
                ('deck_desc', models.TextField(max_length=500)),
                ('visibility', models.CharField(choices=[('P', 'Público'), ('U', 'No listado'), ('R', 'Privado')], default='P', max_length=2)),
                ('format', models.CharField(default='Eterno', max_length=30)),
                ('card_list', models.JSONField(blank=True, default=None)),
                ('deck_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
