# Generated by Django 5.1.4 on 2025-02-06 14:09

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckmodel',
            name='deck_factions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('J', 'Jupiter'), ('M', 'Marte'), ('N', 'Neptuno'), ('P', 'Pluton'), ('S', 'Saturno')], max_length=9),
        ),
    ]
