# Generated by Django 5.1.4 on 2025-02-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckbuilder', '0002_deckmodel_deck_factions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckmodel',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deckmodel',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
    ]
