# Generated by Django 5.1.4 on 2025-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckbuilder', '0004_deckmodel_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckmodel',
            name='format',
            field=models.CharField(default='Sin formato', max_length=30),
        ),
    ]
