# Generated by Django 5.1.6 on 2025-10-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckbuilder', '0005_alter_deckmodel_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckmodel',
            name='deck_desc',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='deckmodel',
            name='last_modified',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deckmodel',
            name='published_date',
            field=models.DateField(editable=False),
        ),
    ]
